### ISSUE TITLE
pred$pred_infections <- pred$sero_estimate

### ISSUE THREAD

**Issue by evanbee** [TheEconomist/covid-19-us-seroprevalence-model#3]
While running your script for purpose of recreating figures from the Economist Dec 10, I ran into a variable (pred$sero_estimate) that seems not to exist.  Am I wrong? Or how can I fix this?

**Comment by sondreus** [comment]
This variable is created on line 101 of the code, with the high and low estimate created on the next two lines. Note that sero_estimate_low being related to ifr_high is intentional, as a low IFR means a high number of infections per death. 

```
  cdc$ifr <- cdc$ifr_estimate
  cdc$sero_estimate <- cdc$deaths*(100/cdc$ifr_estimate)
  cdc$sero_estimate_low <- cdc$deaths*(100/cdc$ifr_high) # opposite necessary here
  cdc$sero_estimate_high <- cdc$deaths*(100/cdc$ifr_low) # opposite necessary here
```
